"""Gates for the generated documentation site under docs/.

docs/ is build output: docs_src/build.mjs turns docs_src/content.mjs into the chapter pages
and the search index. A hand-edit of a built page survives until the next build and then
disappears, and a rebuild that is not committed publishes last release's pages, so the first
gate here holds the committed pages to a fresh build. The rest hold the site to the tree it
documents: its links, its images, the version in its header, and the release notice it owes.
"""
from __future__ import annotations

from html.parser import HTMLParser
from pathlib import Path
import re
import shutil
import subprocess
from urllib.parse import unquote, urlsplit

import pytest
import yaml

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
DOCS_SRC = ROOT / "docs_src"
README = ROOT / "README.md"
BUILD_INPUTS = ("build.mjs", "content.mjs", "serve.mjs", "site-config.mjs")
# Generated by the build; everything else under docs/ is maintained by hand.
GENERATED_ASSETS = ("assets/search-index.js", ".nojekyll")
SITE_BASE = "https://tunabirgun.github.io/bulkseq-studio/"
# "placeholder" in prose is a screenshot that was never taken. These are the sentences that
# use the word for something else; an entry that stops matching is stale and fails below.
ALLOWED_PLACEHOLDER_PHRASES = ("text placeholders and comma-decimal numbers",)
FORBIDDEN_TEXT = (
    "documentation preview",
    "preview is based on",
    "screenshot pending",
    "source candidate",
    "source-candidate",
)
# Generator attribution never belongs in a published page; the product footer of the results
# report is a different document and is not scanned here.
FORBIDDEN_ANYWHERE = ("generated by", "generated with")


def _app_version() -> str:
    text = (ROOT / "app" / "constants.py").read_text(encoding="utf-8")
    match = re.search(r'^APP_VERSION = "([^"]+)"', text, re.MULTILINE)
    assert match, "app/constants.py does not declare APP_VERSION"
    return match.group(1)


def _versions_with_scientific_notice(changelog: str) -> list[str]:
    """Released versions whose changelog section carries the (*scientific*) marker.

    The same derivation tests/test_docs.py makes of the changelog, re-implemented here so
    the two gates cannot drift into agreeing by sharing one wrong reading.
    """
    headings = list(re.finditer(r"^## (\d+\.\d+\.\d+) — \d{4}-\d{2}-\d{2}(?:\s|$)", changelog, re.MULTILINE))
    return [
        match.group(1)
        for index, match in enumerate(headings)
        if "(*scientific*)" in changelog[match.start(): headings[index + 1].start() if index + 1 < len(headings) else len(changelog)]
    ]


class _Page(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.ids: list[str] = []
        self.links: list[str] = []
        self.images: list[dict[str, str]] = []
        self.text: list[str] = []
        self._skip = 0

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        values = {key: value or "" for key, value in attrs}
        if tag in ("script", "style"):
            self._skip += 1
        if values.get("id"):
            self.ids.append(values["id"])
        if values.get("href"):
            self.links.append(values["href"])
        if tag == "img":
            self.images.append(values)

    def handle_endtag(self, tag: str) -> None:
        if tag in ("script", "style") and self._skip:
            self._skip -= 1

    def handle_data(self, data: str) -> None:
        if not self._skip:
            self.text.append(data)

    @property
    def visible_text(self) -> str:
        return " ".join("".join(self.text).split())


def _committed_pages() -> dict[str, str]:
    pages = {path.name: path.read_text(encoding="utf-8") for path in sorted(DOCS.glob("*.html"))}
    assert pages, "documentation gate found no built pages under docs/"
    return pages


def _parsed(pages: dict[str, str]) -> dict[str, _Page]:
    parsed = {}
    for name, source in pages.items():
        page = _Page()
        page.feed(source)
        page.close()
        parsed[name] = page
    return parsed


def _build_output(destination: Path) -> dict[str, str]:
    """Run the site build into a scratch tree and return what it wrote."""
    source = destination / "docs_src"
    source.mkdir(parents=True)
    for name in BUILD_INPUTS:
        shutil.copyfile(DOCS_SRC / name, source / name)
    (destination / "docs" / "assets").mkdir(parents=True)
    subprocess.run(["node", str(source / "build.mjs")], check=True, capture_output=True)
    built = destination / "docs"
    return {str(path.relative_to(built)).replace("\\", "/"): path.read_text(encoding="utf-8")
            for path in sorted(built.rglob("*")) if path.is_file()}


def _committed_build_output() -> dict[str, str]:
    """The committed copies of everything the build writes: the pages and the generated assets."""
    committed = _committed_pages()
    for name in GENERATED_ASSETS:
        path = DOCS / name
        if path.is_file():
            committed[name] = path.read_text(encoding="utf-8")
    return committed


def _build_differences(committed: dict[str, str], fresh: dict[str, str]) -> list[str]:
    differences = []
    for name, text in fresh.items():
        current = committed.get(name)
        if current is None:
            differences.append(f"{name}: the build writes it, docs/ does not carry it")
        elif current != text:
            differences.append(f"{name}: committed file differs from a fresh build")
    for name in sorted(set(committed) - set(fresh)):
        differences.append(f"{name}: no longer produced by the build")
    return differences


def _link_errors(pages: dict[str, str]) -> list[str]:
    parsed = _parsed(pages)
    errors = []
    for name, page in parsed.items():
        for link in page.links:
            parts = urlsplit(link)
            if parts.scheme or parts.netloc:
                continue
            if not link:
                errors.append(f"{name}: empty href")
                continue
            target_name = unquote(parts.path) or name
            if "/" in target_name:
                target = (DOCS / target_name).resolve()
                if not target.is_file():
                    errors.append(f"{name}: missing local reference {link}")
                continue
            if target_name not in pages:
                errors.append(f"{name}: link to a page that does not exist: {link}")
                continue
            if parts.fragment and parts.fragment not in parsed[target_name].ids:
                errors.append(f"{name}: unresolved fragment {link}")
    return errors


def _described_image(pages: dict[str, str]) -> tuple[str, str]:
    """The first image tag the alt-text rule applies to; the logo is exempt from it."""
    for name, source in sorted(pages.items()):
        for tag in re.findall(r"<img\s[^>]*>", source):
            if "bulkseq_logo.svg" not in tag:
                return name, tag
    raise AssertionError("negative-control fixture drifted; no described image in the built site")


def _image_errors(pages: dict[str, str]) -> list[str]:
    errors = []
    for name, page in _parsed(pages).items():
        for image in page.images:
            source = image.get("src", "")
            if not source:
                errors.append(f"{name}: image without a src")
                continue
            if not (DOCS / unquote(urlsplit(source).path)).is_file():
                errors.append(f"{name}: missing image {source}")
            if source.endswith("bulkseq_logo.svg"):
                continue
            if not image.get("alt", "").strip():
                errors.append(f"{name}: image {source} has no alt text")
    return errors


def _version_errors(pages: dict[str, str]) -> list[str]:
    expected = _app_version()
    errors = []
    for name, source in pages.items():
        labels = re.findall(r'class="brand-meta">[^<]*?v(\d+\.\d+\.\d+)', source)
        if len(labels) != 1:
            errors.append(f"{name}: expected exactly one header version label, found {labels}")
        elif labels[0] != expected:
            errors.append(f"{name}: header names v{labels[0]}, APP_VERSION is {expected}")
    return errors


def _wording_errors(pages: dict[str, str]) -> list[str]:
    errors = []
    allowed_seen = {phrase: False for phrase in ALLOWED_PLACEHOLDER_PHRASES}
    for name, page in _parsed(pages).items():
        text = page.visible_text
        lowered = text.lower()
        for phrase in FORBIDDEN_TEXT:
            if phrase in lowered:
                errors.append(f"{name}: stale wording {phrase!r}")
        for phrase in FORBIDDEN_ANYWHERE:
            if phrase in pages[name].lower():
                errors.append(f"{name}: {phrase!r} must not appear in a published page")
        residue = lowered
        for phrase in ALLOWED_PLACEHOLDER_PHRASES:
            if phrase in residue:
                allowed_seen[phrase] = True
                residue = residue.replace(phrase, " ")
        if "placeholder" in residue and "image-slot" not in pages[name]:
            errors.append(f"{name}: 'placeholder' outside a labelled figure placeholder")
    for phrase, seen in allowed_seen.items():
        if not seen:
            errors.append(f"stale allowance: no page uses {phrase!r} any more")
    return errors


def _readme_errors(readme: str, pages: dict[str, str]) -> list[str]:
    parsed = _parsed(pages)
    errors = []
    for link in re.findall(r"\((%s[^)\s]*)\)" % re.escape(SITE_BASE), readme):
        # The site root is served as index.html, so a bare base URL must find that page.
        parts = urlsplit(link[len(SITE_BASE):])
        target = unquote(parts.path) or "index.html"
        if target not in pages:
            errors.append(f"README.md: link into the site does not resolve: {link}")
        elif parts.fragment and parts.fragment not in parsed[target].ids:
            errors.append(f"README.md: unresolved fragment in {link}")
    for link in re.findall(r"\((docs/[^)\s]+)\)", readme):
        if not (ROOT / unquote(link)).is_file():
            errors.append(f"README.md: link to a missing file: {link}")
    return errors


def _catalogue_accessions() -> dict[str, str]:
    """Each bundled study's id, mapped to the accession its catalogue entry declares."""
    catalogue = yaml.safe_load(
        (ROOT / "app" / "data" / "benchmark_datasets.yaml").read_text(encoding="utf-8"))["benchmarks"]
    return {entry["id"]: entry.get("geo_series") or str(entry.get("source_study", "")).split()[0]
            for entry in catalogue}


def _catalogue_errors(pages: dict[str, str]) -> list[str]:
    """Every bundled benchmark study must be listed, by an accession the catalogue declares."""
    listed = " ".join(pages.values())
    errors = []
    for study, accession in _catalogue_accessions().items():
        if not re.fullmatch(r"[A-Z]{3}[A-Z0-9]+", accession or ""):
            errors.append(f"{study}: no usable accession in the catalogue entry")
        elif accession not in listed:
            errors.append(f"{study}: bundled study {accession} is not documented")
    return errors


@pytest.fixture(scope="module")
def fresh_build(tmp_path_factory: pytest.TempPathFactory) -> dict[str, str]:
    if shutil.which("node") is None:
        pytest.skip("node is not installed, so the documentation build cannot be re-run here")
    return _build_output(tmp_path_factory.mktemp("docs-build"))


def test_committed_site_is_a_fresh_build(fresh_build: dict[str, str]) -> None:
    for name in GENERATED_ASSETS:
        assert name in fresh_build, f"the build no longer writes {name}"
    assert _build_differences(_committed_build_output(), fresh_build) == []


def test_build_comparison_rejects_a_hand_edited_page(fresh_build: dict[str, str]) -> None:
    committed = _committed_build_output()
    committed["index.html"] = committed["index.html"].replace("</article>", "<p>edited</p></article>", 1)
    assert any("index.html" in difference for difference in _build_differences(committed, fresh_build))


def test_internal_links_and_anchors_resolve() -> None:
    assert _link_errors(_committed_pages()) == []


@pytest.mark.parametrize(
    ("old", "new", "expected"),
    [
        ('href="guide.html"', 'href="guide-notes.html"', "does not exist"),
        ('href="faq.html#version-notices"', 'href="faq.html#release-notices"', "unresolved fragment"),
        ('href="assets/bulkseq_logo.svg"', 'href="assets/missing.svg"', "missing local reference"),
    ],
    ids=("missing-page", "broken-anchor", "missing-asset"),
)
def test_link_gate_rejects_a_broken_reference(old: str, new: str, expected: str) -> None:
    pages = _committed_pages()
    assert pages["index.html"].count(old) >= 1, f"negative-control fixture drifted; missing {old!r}"
    pages["index.html"] = pages["index.html"].replace(old, new, 1)
    assert any(expected in error for error in _link_errors(pages))


def test_every_image_exists_and_is_described() -> None:
    assert _image_errors(_committed_pages()) == []


@pytest.mark.parametrize(
    ("attribute", "replacement", "expected"),
    [
        (r'alt="[^"]*"', 'alt=""', "has no alt text"),
        (r'\ssrc="[^"]*"', "", "image without a src"),
    ],
    ids=("blank-alt", "absent-src"),
)
def test_image_gate_rejects_an_undescribed_or_sourceless_image(
        attribute: str, replacement: str, expected: str) -> None:
    pages = _committed_pages()
    name, tag = _described_image(pages)
    mutated = re.sub(attribute, replacement, tag, count=1)
    assert mutated != tag, f"negative-control fixture drifted; {tag} carries no {attribute}"
    pages[name] = pages[name].replace(tag, mutated, 1)
    assert any(expected in error for error in _image_errors(pages))


def test_header_names_the_application_version() -> None:
    assert _version_errors(_committed_pages()) == []


def test_version_gate_rejects_a_stale_header() -> None:
    pages = _committed_pages()
    stale = re.sub(r'(class="brand-meta">[^<]*?v)\d+\.\d+\.\d+', r"\g<1>0.0.1", pages["guide.html"], count=1)
    assert stale != pages["guide.html"], "negative-control fixture drifted; no header version label"
    pages["guide.html"] = stale
    assert any("APP_VERSION" in error for error in _version_errors(pages))


def test_faq_names_the_latest_scientific_release() -> None:
    changelog = (ROOT / "CHANGELOG.md").read_text(encoding="utf-8")
    versions = _versions_with_scientific_notice(changelog)
    assert versions, "no released changelog section carries the (*scientific*) marker"
    latest = versions[0]
    faq = _committed_pages()["faq.html"]
    notices = faq.split('id="version-notices"', 1)[1].split("</ul>", 1)[0]
    assert f"<strong>{latest}:</strong>" in notices


def test_no_stale_or_generated_wording() -> None:
    assert _wording_errors(_committed_pages()) == []


@pytest.mark.parametrize("phrase", FORBIDDEN_ANYWHERE)
def test_wording_gate_rejects_generator_attribution(phrase: str) -> None:
    pages = _committed_pages()
    assert "</article>" in pages["index.html"], "negative-control fixture drifted; no article to edit"
    pages["index.html"] = pages["index.html"].replace(
        "</article>", f"<p>{phrase} a tool</p></article>", 1)
    assert any(phrase in error and "published page" in error for error in _wording_errors(pages))


def test_readme_links_into_the_site_resolve() -> None:
    assert _readme_errors(README.read_text(encoding="utf-8"), _committed_pages()) == []


@pytest.mark.parametrize(
    ("link", "expected"),
    [
        (f"{SITE_BASE}guide.html", "does not resolve"),
        (f"{SITE_BASE}faq.html#absent-anchor", "unresolved fragment"),
        ("docs/assets/images/absent.png", "missing file"),
    ],
    ids=("site-page", "broken-anchor", "repository-file"),
)
def test_readme_gate_rejects_a_broken_link(link: str, expected: str) -> None:
    pages = _committed_pages()
    del pages["guide.html"]
    assert _readme_errors(f"[text]({link})", pages) != []
    assert any(expected in error for error in _readme_errors(f"[text]({link})", pages))


def test_every_bundled_benchmark_study_is_documented() -> None:
    assert _catalogue_errors(_committed_pages()) == []


def test_catalogue_gate_rejects_a_renamed_accession() -> None:
    study, accession = next(iter(_catalogue_accessions().items()))
    renamed = re.sub(r"\d", "0", accession)
    assert renamed != accession, f"negative-control fixture drifted; {accession} carries no digits"
    pages = _committed_pages()
    assert any(accession in source for source in pages.values()), \
        f"negative-control fixture drifted; no page names {accession}"
    pages = {name: source.replace(accession, renamed) for name, source in pages.items()}
    assert any(f"{study}: bundled study {accession}" in error for error in _catalogue_errors(pages))
