import { renderLearning } from './learning.mjs';

export function renderHome({ version, routes }) {
  const releases = 'https://github.com/tunabirgun/bulkseq-studio/releases';
  const outputs = [
    ['Plots', 'Differential-expression figures and sample-level views, where your route supports them.', 'outputs.html'],
    ['Enrichment & networks', 'Gene sets and interactive protein relationships.', 'enrichment.html'],
    ['Tables & provenance', 'Results, settings and checks in one record.', 'provenance.html'],
  ];
  return `<section class="hero-new" id="overview" aria-labelledby="hero-title">
    <div class="hero-intro"><p class="eyebrow">Bulk RNA-seq &amp; microarray</p><h1 id="hero-title">Understand each step.<br><em>See what changes.</em></h1><p class="hero-summary">Explore BulkSeq Studio in analysis order: from study design to biological interpretation. Each lesson shows what a setting changes and what it cannot establish.</p><div class="hero-actions"><a class="button primary" href="#download">Download <span aria-hidden="true">↗</span></a><a class="text-link" href="tutorial.html">Quick start <span aria-hidden="true">→</span></a></div><p class="hero-meta">Windows &amp; Linux</p></div>
    ${renderLearning()}
  </section>
  <section class="home-section" id="workflow"><div class="section-heading"><h2>Choose your starting point.</h2></div>
    <div class="route-explorer"><div class="route-tabs js-only" role="tablist" aria-label="Choose an input route">${routes.map((route, i) => `<button type="button" class="route-tab" role="tab" id="tab-${route.id}" data-route="${route.id}" aria-selected="${i === 0}" aria-controls="route-panel" tabindex="${i === 0 ? 0 : -1}">${route.label}</button>`).join('')}</div><div class="route-content" id="route-panel" role="tabpanel" aria-labelledby="tab-public" tabindex="0"><div class="route-heading"><h3 id="route-title">Public accessions</h3><p id="route-description">${routes[0].summary}</p></div><ol class="route-track">${[['Prepare input','Fetch public metadata'],['Process reads','Choose read processing'],['Fit model','Define the comparison'],['Explore results','Read and export results']].map(([title,detail],i)=>`<li><span class="route-node">${i+1}</span><strong>${title}</strong><small>${detail}</small></li>`).join('')}</ol><div class="route-bottom"><p class="route-boundary" hidden>${routes[0].skipped}</p><a class="route-guide text-link" href="walkthrough.html?route=public">View the steps <span aria-hidden="true">↗</span></a></div></div><noscript><p><a href="inputs.html">Read all input routes</a> or <a href="walkthrough.html">open the complete walkthrough</a>.</p></noscript></div>
  </section>
  <section class="home-section" id="outputs"><div class="section-heading"><h2 id="what-it-covers">Explore the result.</h2></div><div class="output-links">${outputs.map(([title,description,href])=>`<a class="output-link" href="${href}"><h3>${title}<span aria-hidden="true">↗</span></h3><p>${description}</p></a>`).join('')}</div><details class="workspace-reveal"><summary><span>View the desktop interface</span><span aria-hidden="true">+</span></summary><figure class="product-shot" data-image-title="The BulkSeq Studio workspace"><img src="assets/images/four-stage-navigator.png" width="1366" height="700" loading="lazy" alt="BulkSeq Studio desktop interface with its four-stage navigator and a synthetic example project open"><figcaption>The desktop application, shown with a synthetic example project.</figcaption></figure></details></section>
  <section class="resources-section" id="where-to-start" aria-labelledby="resources-title"><h2 id="resources-title">Handbook</h2><div class="learn-grid">${[['Quick start','tutorial.html'],['Methods','engines.html'],['Troubleshooting','faq.html']].map(([title,href])=>`<a class="learning-link" href="${href}"><h3>${title}</h3><span aria-hidden="true">↗</span></a>`).join('')}</div></section>
  <section class="download-section" id="download" aria-labelledby="download-title"><div class="download-copy"><p class="eyebrow">Version ${version}</p><h2 id="download-title">Get BulkSeq Studio.</h2><p>Install the app, then prepare its analysis environment.</p><a class="text-link" href="guide.html">Installation guide ↗</a><p class="download-note">Analysis runs locally. Setup, public-data retrieval and online annotation services require connectivity.</p></div><div class="download-options"><a class="download-card" href="${releases}/download/v${version}/BulkSeqStudio-Setup-${version}.exe"><h3>Windows</h3><p>Installer · analysis through WSL2</p><span>Download installer ↗</span></a><a class="download-card" href="${releases}/download/v${version}/BulkSeqStudio-${version}-x86_64.AppImage"><h3>Linux</h3><p>x86_64 AppImage · glibc 2.38+</p><span>Download AppImage ↗</span></a><div class="release-link"><a href="${releases}/tag/v${version}">All packages</a><a href="faq.html#version-notices">Version notes</a><a href="faq.html#cite">License &amp; citation</a></div></div><p class="scope-inline" id="what-it-is-not">For bulk-expression research, not single-cell analysis or clinical diagnosis. Review the study design, checks and interpretation with each result.</p></section>`;
}
